#!/bin/sh
# From gist at https://gist.github.com/chadmaughan/5889802
# to use the pre-commit hook just copy the pre-commit file to .git/hooks/pre-commit
# eg via "cp pre-commit .git/hooks/pre-commit"

# runs spotless and detekt
./gradlew spotlessCheck detekt

# store the exit code of spotlessCheck and detekt in a variable
RESULT=$?

if [ $RESULT != 0 ]
then
    echo "Spotless and/or detekt found some violations, please run the following command to let Spotless try to fix them"
    echo "\n\t ./gradlew spotlessApply\n"
fi

# return the './gradlew spotlessCheck detekt' exit code
exit $RESULT
