include(
        ":app",
        ":core:dagger",
        ":core:kotterknife",
        ":core:model",
        ":lib:arch",
        ":lib:epoxy",
        ":lib:resource",
        ":lib:service:tmdb:tmdbcore",
        ":lib:service:tmdb:tmdbmock",
        ":lib:service:tmdb:tmdbremote",
        ":feature:browser",
        ":feature:detail"
)
