include(
        ":app",
        ":core:dagger",
        ":core:kotterknife",
        ":lib:arch",
        ":lib:datasource:tmdb",
        ":lib:epoxy",
        ":lib:resource",
        ":lib:remote",
        ":feature:browser",
        ":feature:detail"
)
